pub use super::i_vm::*;

#[cxx::bridge]
mod ffi {
	extern "C++" {
		type lua_State = crate::raw::i_vm::lua_State;

		pub unsafe fn luau_load(state: *mut lua_State, chunk_name: *const c_char, bytecode: *const c_char, size: u64, env: i32) -> i32;
		pub unsafe fn luaL_checkoption(state: *mut lua_State, arg: i32, def: *const c_char, list: *const *const c_char) -> i32;
	}
}

// Overwrite autogenerated bindings with the raw bindings.
pub use ffi::{luau_load, luaL_checkoption};